Inventory API
elwyncrestha/webcare-backend pull request #16
Opened 2020-06-29 12:27 UTC by Mohammadhussain257

API for managing inventory items.

2020-06-29 16:42 UTC, elwyncrestha requested changes
Add changeset of inventory as well.

2020-06-29 16:42 UTC, elwyncrestha commented on pemits-api/src/main/java/com/pemits/webcare/api/inventory/repository/spec/InventorySpecBuilder.java
> +        return null;
Return `InventorySpec` instead of `null`.

2020-06-29 16:42 UTC, elwyncrestha commented on pemits-api/src/main/java/com/pemits/webcare/api/inventory/service/InventroyServiceImpl.java
> +        return null;
Return `InventorySpecBuilder` instead of `null`.

2020-06-29 16:42 UTC, elwyncrestha commented on pemits-api/src/main/java/com/pemits/webcare/api/inventory/service/InventroyServiceImpl.java
> +public class InventroyServiceImpl extends BaseServiceImpl<Inventory, Long> implements InventoryService {
Fix the typo `InventroyServiceImpl `.

2020-06-30 02:07 UTC, Mohammadhussain257 commented on pemits-api/src/main/java/com/pemits/webcare/api/inventory/service/InventroyServiceImpl.java
> +public class InventroyServiceImpl extends BaseServiceImpl<Inventory, Long> implements InventoryService {
Okay

2020-06-30 02:51 UTC, Mohammadhussain257 commented
Request changes has been completed, review required

2020-06-30 02:52 UTC, elwyncrestha reviewed
> Request changes has been completed, review required

@Mohammadhussain257 changeset is incorrect.

2020-06-30 02:52 UTC, elwyncrestha commented on pemits-web/src/main/resources/db/changelog/changelog-master.xml
> +      <column name="purchaseDate" type="DATE"/>
`totalPrice` should be `total_price`, Same case with `purchaseDate`. Hibernate uses **Snake Case**

2020-06-30 05:12 UTC, elwyncrestha approved these changes

2020-06-30 05:12 UTC, merged